[package]
name = "roguelike"
version = "0.1.0"
edition = "2021"

[dependencies]
rltk = { git = "https://github.com/amethyst/bracket-lib" }
specs = "0.17.0"
specs-derive = "0.4.1"
rand = {version = "0.8.5", default-features = false }
wasm-bindgen = "0.2.80"